<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="appsettings.*.json">
        <DependentUpon>appsettings.json</DependentUpon>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BasicOnlineShoppingService.Modules.CartModule\BasicOnlineShoppingService.Modules.CartModule.csproj" />
      <ProjectReference Include="..\BasicOnlineShoppingService.Modules.OrderModule\BasicOnlineShoppingService.Modules.OrderModule.csproj" />
      <ProjectReference Include="..\BasicOnlineShoppingService.Modules.Report\BasicOnlineShoppingService.Modules.Report.csproj" />
      <ProjectReference Include="..\BasicOnlineShoppingService.Modules.StoreModule\BasicOnlineShoppingService.Modules.StoreModule.csproj" />
    </ItemGroup>

</Project>
